# Logistic Regression Assignment (due 26 November)

In this practical you will learn how to apply logistic regression to the task of predicting two digits from the MNIST database: http://yann.lecun.com/exdb/mnist/. The database contains 60000 train images containing digits and 10000 test images. The images are of size 28 × 28. We will use the images in a vectorized form: a vector of size of 784. The code extracting the digits 0 and 1 is provided in the stubs.


In [1]:
%tensorflow_version 2.x

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [2]:
import tensorflow as tf
import tensorflow_datasets as tfds

In [3]:
print(tf.__version__)


2.12.0


In [4]:
import numpy as np 

In [5]:
def data_preprocess(images, labels):

    # number of examples m  
    m = images.shape[0]
    
    print(m)
    # create vector of ones to concatenate to our data matrix (for intercept terms)
    ones = np.ones(shape=[m, 1])
    images = np.concatenate((ones, images), axis=1)
    
    # to retrieve the images and corresponding labels where the label is either 0 or 1, 
    # we define two logical vectors that can be used to subset our data_matrices
    logical_mask_0 = labels == 0
    logical_mask_1 = labels == 1
    
    images_zeros = images[logical_mask_0]
    labels_zeros = labels[logical_mask_0]
    images_ones = images[logical_mask_1]
    labels_ones = labels[logical_mask_1]
    
    X = np.concatenate((images_zeros, images_ones), axis=0)
    y = np.concatenate((labels_zeros, labels_ones), axis=0)
    
    # shuffle the data and corresponding labels in unison
    def _shuffle_in_unison(a, b):
        assert len(a) == len(b)
        p = np.random.permutation(len(a))
        print('length ', len(a))
        print(a.shape)
        print(a[p].shape)
        return a[p], b[p]

    return _shuffle_in_unison(X,y)   

In [6]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train, x_test = x_train / 255.0, x_test / 255.0


11490434/11490434 [==============================] - 1s 0us/step


In [7]:
print (x_train.shape)

(60000, 28, 28)


In [8]:
x_train = x_train.reshape([60000,784])
x_test = x_test.reshape([10000,784])
print(x_train.shape)


(60000, 784)


In [9]:
X,y = data_preprocess(x_train, y_train)
print('shape: ', X.shape)
print('shape: ', y.shape)

60000
length  12665
(12665, 785)
(12665, 785)
shape:  (12665, 785)
shape:  (12665,)


Define hyperparams: learning rate and gradient descent steps


In [10]:
learning_rate = 0.01
gdc_steps = 1000

    

Initialize your parameters W


In [11]:
# number of features n
n = X.shape[1]
print(n)
# we need to define our model parameters to be learned. we use W (weights) instead of theta this time.
mu, sigma = 0, 0.01 # mean and standard deviation
w = np.random.normal(mu, sigma, n)


785


In [12]:
print(X.shape, w.shape)

(12665, 785) (785,)


Define the sigmoid function, your code here:


In [13]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

Define the loss function as provided in equation 12 (Logistic regression slides)


In [14]:
def compute_cross_entropy_loss(y, y_hat):
      return   -1 * y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat)



Start optimization. During training you minimize the loss function. In every iteration your loss should decrease. You also want to look how many correct predictions you have at every iteration. Reminder: the belonging to class digit 1 is when your prediction, $\hat y$ is greater or equal to 0.5. 

When you test your prediction vector (containing zero and ones) with the labels (also zero and ones) you can use the equal function. 

Example:
prediction = (1, 0, 1, 1) and the true labels are y = (0, 0, 1, 0).

When you test on equality you get following result: correct = (0, 1, 1, 0). Your accuracy is: 0+1+1+0
4 = 0.5.
You compute the accuracy for the training and test.

In [15]:
for step in range(0, gdc_steps):
    print("Performing step " + str(step) + " of gradient descent.")
    # perform the dot product between the weights and the examples
    z = np.dot(X,w)
    print('z', z, z.shape)
    # apply the nonlinearity
    y_hat = sigmoid(z)
    print("y hat: " + str(y_hat))
    # normally normalized with -1/m 
    loss = compute_cross_entropy_loss(y, y_hat)
    print("Loss at step " + str(step) + ": " + str(loss))
    
    # compute the error term, i.e. the difference between labels and estimated labels y_hat, see equation 24 in the slides
    error_term = y_hat - y
    
    # compute the gradient. as our data matrix X is currently layed out as X_j_i, we got to transpose it 
    # see derived formula of the gradient calculation
    gradients =  np.dot(np.transpose(X),error_term)
    print(X.shape)
    print(error_term.shape)
    print(gradients.shape)
    
    # update w using the gdc update rule
    w = w-learning_rate*gradients
    
    # compute the predictions and cast them to int values
    predictions = (y_hat>0.5).astype(np.int32)
    print(predictions)
    print(predictions.shape)
    # compute mean accuracy
    accuracy =  np.mean(predictions == y)
    print("Accuracy at step " + str(step) + ": " + str(accuracy))
    


Performing step 0 of gradient descent.
z [-0.05775666 -0.03851479 -0.02713634 ...  0.01609644  0.21846231
  0.14053149] (12665,)
y hat: [0.48556485 0.49037249 0.49321633 ... 0.50402402 0.5543994  0.53507517]
Loss at step 0: [ 0.72244243  0.71258999 -0.67967106 ...  0.68513135 -0.80833223
 -0.76587953]
(12665, 785)
(12665,)
(785,)
[0 0 0 ... 1 1 1]
(12665,)
Accuracy at step 0: 0.21208053691275167
Performing step 1 of gradient descent.
z [  395.25003174   359.19102531 -1206.32002915 ...   471.91805344
 -1838.09761072 -1895.41270448] (12665,)
y hat: [1. 1. 0. ... 1. 0. 0.]
Loss at step 1: [nan nan nan ... nan nan nan]
(12665, 785)
(12665,)
(785,)
[1 1 0 ... 1 0 0]
(12665,)
Accuracy at step 1: 0.9883932096328464
Performing step 2 of gradient descent.
z [  420.63273601   378.62171906 -1171.67890631 ...   505.3763352
 -1791.48413514 -1835.25044447] (12665,)
y hat: [1. 1. 0. ... 1. 0. 0.]
Loss at step 2: [nan nan nan ... nan nan nan]
(12665, 785)
(12665,)
(785,)
[1 1 0 ... 1 0 0]
(12665,)
Acc

<ipython-input-13-dc64dee5606b>:2: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
<ipython-input-14-c6e70183a7ea>:2: RuntimeWarning: divide by zero encountered in log
  return   -1 * y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat)
<ipython-input-14-c6e70183a7ea>:2: RuntimeWarning: invalid value encountered in multiply
  return   -1 * y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat)


Die letzten 5000 Zeilen der Streamingausgabe wurden abgeschnitten.
 0.00000000e+000 0.00000000e+000]
Loss at step 583: [nan nan  0. ... nan nan nan]
(12665, 785)
(12665,)
(785,)
[1 1 0 ... 1 0 0]
(12665,)
Accuracy at step 583: 0.9993683379392025
Performing step 584 of gradient descent.
z [  266.71472147   291.79273024  -545.64768886 ...   317.7012797
  -931.44102496 -1135.72364307] (12665,)
y hat: [1.00000000e+000 1.00000000e+000 1.06713574e-237 ... 1.00000000e+000
 0.00000000e+000 0.00000000e+000]
Loss at step 584: [nan nan  0. ... nan nan nan]
(12665, 785)
(12665,)
(785,)
[1 1 0 ... 1 0 0]
(12665,)
Accuracy at step 584: 0.9993683379392025
Performing step 585 of gradient descent.
z [  266.42087833   291.64432533  -545.373727   ...   317.37957587
  -930.91455803 -1135.2626685 ] (12665,)
y hat: [1.00000000e+000 1.00000000e+000 1.40345919e-237 ... 1.00000000e+000
 0.00000000e+000 0.00000000e+000]
Loss at step 585: [nan nan  0. ... nan nan nan]
(12665, 785)
(12665,)
(785,)
[1 1 0 ... 1 0 

Evaluate model on test set

In [16]:
print("_______________________________")
print("Starting evaluation of test set")

X,y = data_preprocess(x_test, y_test)
z = np.dot(X,w) 
y_hat = sigmoid(z)
predictions = (y_hat>0.5).astype(np.int32)
accuracy = np.mean(predictions==y)
print("Accuracy of test set: " + str(accuracy))

_______________________________
Starting evaluation of test set
10000
length  2115
(2115, 785)
(2115, 785)
Accuracy of test set: 1.0


<ipython-input-13-dc64dee5606b>:2: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
